#!/bin/bash

# Welcome to the Linux Command Line Course!

# --- Introduction to Linux ---
echo "Welcome to the Introduction to Linux section!"
echo "Linux is a powerful, open-source operating system kernel."
echo "It's the foundation for many popular operating systems, like Ubuntu, Fedora, and Android."
echo "Linux is known for its stability, security, and flexibility, making it a favorite for servers, developers, and power users."
echo "In this course, we'll focus on the command line interface (CLI), a powerful way to interact with a Linux system."
echo "---------------------------------
"

# --- Navigating the File System ---
echo "Let's learn to navigate the file system."
echo "The file system is a tree-like structure of directories and files."
echo "Your current location is your 'present working directory' (pwd)."
echo "Use 'pwd' to see where you are:"
echo "  pwd"
echo "
To see the contents of your current directory, use 'ls':"
echo "  ls"
echo "
To see more details, like permissions and ownership, use 'ls -l':"
echo "  ls -l"
echo "
To change your directory, use 'cd'. For example, to go to the root directory:"
echo "  cd /"
echo "
To go to your home directory, you can use 'cd' with no arguments or 'cd ~':"
echo "  cd"
echo "---------------------------------

# --- Working with Files and Directories ---
echo "Now, let's learn to work with files and directories."
echo "To create a new, empty file, use the 'touch' command:"
echo "  touch new_file.txt"
echo "
To create a new directory, use the 'mkdir' command:"
echo "  mkdir new_directory"
echo "
To remove a file, use the 'rm' command. Be careful, this is permanent!"
echo "  rm new_file.txt"
echo "
To remove an empty directory, use 'rmdir':"
echo "  rmdir new_directory"
echo "
To remove a directory and all its contents, use 'rm -r':"
echo "  rm -r new_directory"
echo "
To copy a file, use 'cp'. You need to provide a source and a destination:"
echo "  cp source_file.txt destination_file.txt"
echo "
To move or rename a file, use 'mv'."
echo "To rename a file:"
echo "  mv old_name.txt new_name.txt"
echo "To move a file to a different directory:"
echo "  mv my_file.txt /home/user/documents/"
echo "---------------------------------

# --- Understanding Permissions ---
echo "Let's dive into file permissions."
echo "Every file and directory in Linux has permissions for three types of users:"
echo "  - The owner of the file (u)"
echo "  - The group the file belongs to (g)"
echo "  - Everyone else (o)"
echo "
There are three types of permissions:"
echo "  - Read (r) - permission to view the contents of a file or list the contents of a directory"
echo "  - Write (w) - permission to change the contents of a file or create/delete files in a directory"
echo "  - Execute (x) - permission to run a file as a program or enter a directory"
echo "
When you run 'ls -l', you'll see a string like '-rwxr-xr--'."
echo "The first character indicates the file type (- for a file, d for a directory)."
echo "The next three characters are the owner's permissions (read, write, execute)."
echo "The next three are the group's permissions."
echo "The final three are for everyone else."
echo "
To change permissions, we use the 'chmod' command."
echo "You can add or remove permissions for different users."
echo "For example, to give the owner execute permission:"
echo "  chmod u+x my_script.sh"
echo "
To remove write permission from the group and others:"
echo "  chmod go-w my_file.txt"
echo "
You can also set permissions using numbers."
echo "r=4, w=2, x=1.  Add them up for each user type."
echo "For example, to set permissions to 'rwxr-xr--' (owner can read/write/execute, group can read/execute, others can only read):"
echo "  chmod 754 my_file.txt"
echo "---------------------------------

# --- Shell Scripting Basics ---
echo "Now let's get started with shell scripting!"
echo "A shell script is a text file containing a series of commands."
echo "The shell reads this file and executes the commands in order."
echo "
Let's create a simple script. Create a file named 'hello.sh' with the following content:"
echo "
  #!/bin/bash"
echo "  echo \"Hello, World!\""
echo "
The first line, '#!/bin/bash', is called a 'shebang'. It tells the system to execute the script with bash."
echo "
To run our script, we first need to make it executable."
echo "We use the 'chmod' command we learned about earlier:"
echo "  chmod +x hello.sh"
echo "
Now, you can run the script like this:"
echo "  ./hello.sh"
echo "
This will execute the commands in the script and print 'Hello, World!' to the screen."
echo "This is just the beginning of what you can do with shell scripting!"
echo "---------------------------------

echo "Congratulations! You have completed the Linux Command Line Basics course."
